### ISSUE TITLE
Težava pri nalaganju knjižnice ggplot2

### ISSUE THREAD

**Issue by VidicL13** [VidicL13/APPR-2015-16#2]
pravkar sem poskušal zagnati knjižnico ggplot2 in mi je vrnilo napako: library("ggplot2", lib.loc="~/R/win-library/3.2")
Error in get(Info[i, 1], envir = env) : 
  cannot open file 'C:/Users/Luka/Documents/R/win-library/3.2/plyr/R/plyr.rdb': No such file or directory
Error: package or namespace load failed for ‘ggplot2’

Poskusil sem s ponovnim nalaganjem knjižnice, vendar tudi to ni pomagalo. uporabljam R verzije 3.2.2. in bi lepo prosil za še kakšen nasvet, kako rešiti to težavo. 
Tudi ko sem šel pregledat mape v "C:/Users/Luka/Documents/R/win-library/3.2/plyr/R" nisem našel fila "plyr.rdb". lahko da pri instalaciji knjižnice pride do napake. kako bi lahko to odpravil?

**Comment by jaanos** [comment]
Takole na hitro bi ti svetoval, da ponovno namestiš knjižnico `plyr` - pri meni je nameščena različica 1.8.2, kar lahko sam preveriš z ukazom

``` R
packageVersion("plyr")
```

Če imaš starejšo verzijo, torej knjižnico še enkrat namesti.

**Comment by VidicL13** [comment]
hvala

**Comment by jaanos** [comment]
Ko razrešiš problem, se spodobi, da issue zapreš. Tako bo lažje slediti problemom, ki se bodo sproti pojavljali.

**Comment by VidicL13** [comment]
Se opravicujem.
28. nov. 2015 17:28 je oseba "Janoš Vidali" notifications@github.com
napisala:
