### ISSUE TITLE
Povezave do podatkov

### ISSUE THREAD

**Issue by jaanos** [VidicL13/APPR-2015-16#4]
V opisu projekta nimaš povezave do podatkov, s katerimi boš delal. Tako te prosim, da dodaš povezavo do spletne strani, kjer si jih pridobil.

Ko sprejmeš pull request #3, boš lahko podatke tudi naložil v repozitorij.

**Comment by VidicL13** [comment]
najlepša hvala za pomoč. Kar pa se tiče povezav, sem pa ravno včeraj in danes urejal vse te stvari. Nisem jih še commital, ker sem želel prvo stvari spraviti vsaj do takega nivoja, da bo delovalo. Ker dvomim, da mi bo to uspelo še nocoj, bom poslal commit in push sele jutri.

**Comment by jaanos** [comment]
Ni problema - sicer pa ni nič narobe s tem, če commitaš in pushaš še nedokončano delo - navsezadnje gre tukaj za shranitev vmesnega stanja in sinhronizacijo med več računalniki (po "bontonu" bi sicer moral nedokončano delo imeti v posebni veji, a se za potrebe tega projekta s tem ni potrebno ukvarjati.).

**Comment by VidicL13** [comment]
so bom morda jutri poigral in poskusil ustvariti novo vejo, če ne zaradi drugega, zaradi vaje.
