### ISSUE TITLE
Težava pri zbiranju podatkov.

### ISSUE THREAD

**Issue by VidicL13** [VidicL13/APPR-2015-16#6]
Pozdravljeni, naletel sem na težavo, ko sem želel pobrati podatke s spletne strani. Ko sem želel narediti novo tabelo, sem dobil napačne podatke. Če bi želel prejeti prave, bi moral nekako klicati 

```
javascript:_DoPostBack('fcc1$dgrC$ctl76$lkbr',")
```

kar bi mi vrnilo iskane podatke. Tukaj se pa zatakne, saj ne znam poiskati nadomestnega ukaza, ki bi počel isto kakor `_DoPostBack()` iz javascripta. Spodaj dodajam še svojo kodo.

``` r
naslov <- "http://www.fasteconomicnews.com/fx_calendar.aspx"
prebrano <- read_html(naslov, encoding = "UTF-8")
tabela <- prebrano %>% html_node(xpath = '//*[@id="fcc1_dgrC"]') %>% 
  html_table(header = TRUE)
```

**Comment by jaanos** [comment]
Če pogledaš v source, vidiš, da funkcija `__DoPostBack` pošlje obrazec `theForm`:

``` javascript
function __doPostBack(eventTarget, eventArgument) {
    if (!theForm.onsubmit || (theForm.onsubmit() != false)) {
        theForm.__EVENTTARGET.value = eventTarget;
        theForm.__EVENTARGUMENT.value = eventArgument;
        theForm.submit();
    }
}
```

Iz originalnega dokumenta bo torej potrebno dobiti vrednosti polj v obrazcu, polji `__EVENTTARGET` in `__EVENTARGUMENT` pa nastaviti na vrednosti, ki ju dobi `__doPostBack`:

``` R
library(rvest)
library(dplyr)
library(gsubfn)
library(httr)
naslov <- "http://www.fasteconomicnews.com/fx_calendar.aspx"
prebrano <- read_html(naslov, encoding = "UTF-8")
html_tabela <- prebrano %>% html_node(xpath = '//*[@id="fcc1_dgrC"]')
tabela <- html_tabela %>% html_table(header = TRUE)

viewstate <- prebrano %>%
  html_node(xpath = '//input[@id="__VIEWSTATE"]/@value') %>%
  html_text()
viewstategen <- prebrano %>%
  html_node(xpath = '//input[@id="__VIEWSTATEGENERATOR"]/@value') %>%
  html_text()
validation <- prebrano %>%
  html_node(xpath = '//input[@id="__EVENTVALIDATION"]/@value') %>%
  html_text()
```

Če veš točno, katera povezava te zanima, lahko potem uporabiš njene podatke, sicer pa si lahko pobereš seznam vseh povezav:

``` R
povezave <- html_tabela %>%
  xml_nodes(xpath='.//a[@id]/@href') %>%
  html_text() %>% strapplyc("'([^']*)'")
```

Sedaj lahko narediš zahtevek POST z ustreznimi podatki in dobljeno stran obdelaš na podoben način:

``` R
podstran <- POST(naslov, body = list(
    "__EVENTTARGET" = povezave[[1]][1],
    "__EVENTARGUMENT" = povezave[[1]][2],
    "__LASTFOCUS" = "",
    "__VIEWSTATE" = viewstate,
    "__VIEWSTATEGENERATOR" = viewstategen,
    "__EVENTVALIDATION" = validation
  ), encode = "form") %>% read_html()

tabela2 <- podstran %>%
  html_node(xpath = '//*[@id="fcc1_dgrC"]') %>%
  html_table(header=TRUE)
```

Tukaj je podan primer, ko pobereš eno samo podstran; če bi jih hotel več, greš lahko seveda z zanko `for` skozi seznam `povezave`.

**Comment by VidicL13** [comment]
hvala za pomoč, mislim da se bom naprej lažje znašel
