### ISSUE TITLE
Velikost črk in poročilo

### ISSUE THREAD

**Issue by jaanos** [VidicL13/APPR-2015-16#7]
V poročilu kličeš programa `lib/knjiznice.r` in `uvot/uviz_podatkov.r`, a imata ustrezni datoteki končnico `.R` (velika črka!). Tako napiši tudi pri klicanju, saj so nekateri sistemi občutljivi na velikost črk.

V poročilo dodaj seveda še kak graf. Najbolje, da imaš v svojem projektu (oziroma vsaj v vrhnjem imeniku) eno samo datoteko s končico `.Rmd`, da bo takoj jasno, kje je pravno poročilo.

**Comment by VidicL13** [comment]
hvala za info in bom popravil, vendar danes ne bom utegnil.

**Comment by jaanos** [comment]
Ni problema - seveda pa to le uredi jutri, da boš imel pripravljeno poročilo za predstavitev v sredo. Glede na to, da tega še nisi uredil, bi se spodobilo, da issue pustiš odprt.

**Comment by VidicL13** [comment]
to pa vsekakor bom, samo bom pripravil drugačno vmesno poročilo, ki bo zajemalo le bistvo, da ne bom predolg
